### ISSUE TITLE
[PAUSED] - Convert the project according yeoman standard generation

### ISSUE THREAD

**Issue by amanganiello90** [ibbatta/readme-generator#29]
Hi @ibbatta... Great job! But I have some advices to improve your generator.
I have seen that you have issues about unit tests, more option, and so on.
Therefore I recommend you to convert your generator as a **yeoman project**, in order to resolve some problems using standard tools and solutions.
You can emulate some of my projects, and in particular my [api generator](https://github.com/fullStackApp/generator-full-stack-api).
For any questions, feel you free to ask me, I will be very happy to share my experience about javascript and open source world :)

**Comment by ibbatta** [comment]
Hi @amanganiello90 ,

I've started reading [this section](https://yeoman.io/authoring/index.html) and, probably, I will refactor my code to fulfill the yeoman standards (but for the future version 2.0, because it's a huge amount of work).

Thanks a lot for you suggestion!
