### ISSUE TITLE
Non-Node projects compatibility

### ISSUE THREAD

**Issue by christianascone** [ibbatta/readme-generator#33]
**Is your feature request related to a problem? Please describe.**
This generator could be used for non-node projects.

**Describe the solution you'd like**
A shell flag to choose the configuration json location and an option for generic package manager .
It is ok to use the package.json format, but in a different project, like python project, I could have a readme.json file used only by generator.

**Comment by ibbatta** [comment]
Hi @christianascone ,

thanks for your suggestion.
Actually I am working to enhance the tool in case the user doesn't have a package.json.

My idea is to replace the main informations request by questions prompted with `inquirer` (I am still evaluating if this would be annoying or not for the final user)

**Comment by christianascone** [comment]
Thank you for your reply.
Yeah, it could be a bit annoying (imho).
I love the way this project reads 90% info from file but I understand the missing json problem.

You could otherwise ask basic info with `inquirer` (like project name and project description) finally generating a simple package.json.

**Comment by ibbatta** [comment]
@christianascone you are right.
At the moment, the information I really need to generate the README.md are: `['name',
  'version',
  'description',
  'repository',
  'author',
  'engines',
  'dependencies',
  'contributors']`

If asking for each of them is annoying, I could add a flag (like `-e`, `--entry`) where a user could define another entry file (but the json structure must be the same as specified in readme)

**Comment by christianascone** [comment]
The `-entry` (or another one) flag for entry file would be very interesting as starting point for non-node projects.

**Comment by ibbatta** [comment]
@christianascone ok fine so :) I will implement it asap.

**Comment by ibbatta** [comment]
@christianascone I've published the feature. Now the correct (and current) version is **0.1.0**

**Comment by christianascone** [comment]
@ibbatta Thank you very much. I'll give it a try
