### ISSUE TITLE
Version 0.1.1 not working when installed globally

### ISSUE THREAD

**Issue by christianascone** [ibbatta/readme-generator#37]
**Describe the bug**
I cannot run version 0.1.1 when installed globally.

**To Reproduce**

1. npm install -g @ibbatta/readme-generator@0.1.0
2. readme-generator
3. See error

```
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '../internals/to-indexed-object'
Require stack:
- /usr/local/lib/node_modules/@ibbatta/readme-generator/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@ibbatta/readme-generator/dist/index.js:2:207)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@ibbatta/readme-generator/dist/index.js'
  ]
}
```

**Desktop (please complete the following information):**

- OS: [MacOS Mojave]
- Version [10.14.6]

**Additional context**
Downgrading to 0.0.1 or 0.1.0 it works

**Comment by ibbatta** [comment]
Hi @christianascone ,

thanks for the issue.
I see that you tried to install @ibbatta/readme-generator@**0.1.0** (instead of **0.1.1**), is this a typo?

Anyway I will check this error asap (I am not at home at the moment, sorry)

**Comment by christianascone** [comment]
@ibbatta  Thanks.
I tried any version I found in [this page](https://www.npmjs.com/package/@ibbatta/readme-generator).

- 0.0.1: Working ✅ 
- 0.1.0: Working ✅ 
- 0.1.1: NOT working 🔴

**Comment by ibbatta** [comment]
@christianascone I found the problem.
The node version (**8.9.0**) is too old and must be upgrade at least at the LTS 10.16.x
I will upgrade the node engine required in package.json (this is the quickest way I found to fix this error). Thanks for reporting!

**Comment by ibbatta** [comment]
@christianascone **FIXED** (could you give a try as soon as you can?)

**Comment by christianascone** [comment]
@ibbatta  Thank you very much.
Could you publish the new version?
I'm currently trying the published package.

**Comment by ibbatta** [comment]
@christianascone i've release the 0.1.2 :)

**Comment by christianascone** [comment]
Perfectly working

**Comment by ibbatta** [comment]
Pheew... nice!
Thanks a lot sir.

:star:  ヽ( ´ ∇ ｀ )ノ :star:
