### ISSUE TITLE
[EASY LEVEL] - Check and fix README.md

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/readme-generator#38]
For this `#hacktoberfest` event I am looking for someone who help me fixing my readme.md (if needed).

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by Toby56** [comment]
Can I attempt this quickly please?

**Comment by ibbatta** [comment]
> Can I attempt this quickly please?

Sure!

**Comment by Toby56** [comment]
Thanks! Do you mainly want grammar fixed or more than that?

**Comment by ibbatta** [comment]
@Toby56 mainly grammar (but I'll be glad to hear if you have suggestions about how to improve the readme, or change some parts)

**Comment by Toby56** [comment]
Okay!

**Comment by Toby56** [comment]
I've done my best: #42

**Comment by Toby56** [comment]
Took you a while

**Comment by ibbatta** [comment]
@Toby56 Sadly, I was a lot busy in the past weeks. My bad.
